### ISSUE TITLE
Only Abstract Base Classes are imported from collections.abc

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#102]
remove incorrect code like:
try:
    from collections.abc import defaultdict
except ImportError:
    from collections import defaultdict

The above will always enter the except part for
namedtuple 
deque 
ChainMap
Counter 
OrderedDict
defaultdict 
UserDict 
UserList
UserString

The above are not Abstract Base Classes  and are not move to collections.abc!

The rest are Deprecated but the removal has been delayed until 3.9 now
source: https://docs.python.org/3.8/library/collections.html
See: 
https://docs.python.org/3.6/library/collections.abc.html#module-collections.abc

**Comment by rowleya** [comment]
Although the message is confusing, I believe that collections will still be available for the foreseeable future, but the move of the actual Abstract Base Classes is the part that will change i.e. it will still be possible to use collections.default_dict in 3.9 onwards, but not collections.Set (which will become collections.abc.Set).

**Comment by Christian-B** [comment]
The issue is that I moved namedtuple, deque, ChainMap, Counter, OrderedDict, defaultdict, UserDict, UserList, or UserString from abc and these have not and will not move.
