### ISSUE TITLE
ExecutableFinder log directories and paths.

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#120]
We currentkly have no idea how many of our ninaries are touched by the integration tests,

We should get ExecutableFinder to log in a centralized path which directories hold binaries and which binaries have been asked for,

The write a tool to repport the percentage of binaries used.

**Comment by andrewgait** [comment]
It's certainly true that some of the less-used models (IF_curr_delta and IF_curr_alpha come to mind immediately) aren't covered by the integration tests directly (they are "tested" in the sense that there are examples that use them in PyNN8Examples, but there should probably be integration tests for them too).

**Comment by Christian-B** [comment]
The cron job runs all PyNN8Examples execpt those listed in 
https://github.com/SpiNNakerManchester/sPyNNaker8/blob/master/p8_integration_tests/scripts_test/build_script.py
as taking too long.
See "Run scripts" step

So an intergeation test that does no more checking than does a script run is not required.

**Comment by Christian-B** [comment]
Work in progress under https://github.com/SpiNNakerManchester/SpiNNUtils/pull/121

**Comment by Christian-B** [comment]
fixed by https://github.com/SpiNNakerManchester/SpiNNUtils/pull/121
