### ISSUE TITLE
CFG files in every repository

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#148]
We have the ConfigHolder and methods that need vales can acess that directly.
https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/config_holder.py

There are two issue witht he current setup.
1. Pacman and FEC share a singe cfg file, so values only needed in FEC are in https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/spinnaker.cfg
2. There is no access at the SpinMan and SpinMachine so one that need still have to be passed down.

An idea is to 
1.Move config_holder.py to SpinUtils.
2. Add a cfg file in each reposotory
3. Add a stack of ConfigLoader classes on top of config_holder.py which attach their cfg file.
4. Unittest which depend on config can call their config_loader to make sure the right cfg files are loaded
4. UnitTests which depend on a . template value such as [Machine] ones must specifically add then (romoving them in a teardown)
5. sim.setup would call config loader agian make sure the right cfg files are loader

**Comment by rowleya** [comment]
Sounds reasonable.  It may be that you don't need one in *every* repository, only those that have configs (though equally empty config files would be OK).

**Comment by Christian-B** [comment]
I think I will do empty cfg in all repositories Spynnaker (and GFE) depend on 
1. It is more consistent
2. Confirms there are no new values required here
3. Easier for people to add a cfg value if needed later.

I was NOT planning on doing cfg files above Spynnaker/ GFE as
1. Not sure it is needed
2. They would have to ensure this cfg files is added before setup

**Comment by rowleya** [comment]
Yes that sounds OK.  One issue is the ordering of cfg files from things that are "at the same level" in the hierarchy e.g. PACMAN, DataSpecification, SpiNNMan.  There shouldn't be a conflict, but is it worth checking for that?

**Comment by Christian-B** [comment]
yes the FEC need to be sure to add all the cfg files without loosing slots.
I think I can do that by having FEC config_loader only inherit from pacman but also add the DataSpecification, SpiNNMan cfg files in.
