### ISSUE TITLE
cfg validation not works well

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#151]
The conf_loader had an option to validate the users cfg file.

However it was not used in Spynnaker and for GFE while it a appeared to be active it was not.

When I fixed it it gave error messages I am not sure we should throw.

For example it failed because of a now extra
default_application_file_path =...

So we should either fix validation or nuke validation.

If fix it the question is if an incorrect value is found raise an exception or just log a warning.
Currently we raise an exception but I prefer just log a warning.

**Comment by rowleya** [comment]
Happy to log a warning in general, but if it in fact isn't really doing what we want, it probably isn't that useful.

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNUtils/pull/154
