### ISSUE TITLE
register_binary_search_path ignores bad path

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#176]
ExecutableFinder.add_path

called by register_binary_search_path

silently ignores all Exceptions.

Should it not at least log?

**Comment by rowleya** [comment]
That appears to come from the binary logging code addition; I assume this was done as that is not important to be correct!

**Comment by Christian-B** [comment]
ah yes I agree. That is under the category nice to have log info dont kill the run if it fails.
