### ISSUE TITLE
With ProgressBar not working

### ISSUE THREAD

**Issue by Andrewwango** [SpiNNakerManchester/SpiNNUtils#25]

**Comment by Christian-B** [comment]
Actaully created Christian. I had not spotted Andrew's account still logged in.

**Comment by Christian-B** [comment]
Donal has started using progress_bar with but has not added the required __enter__ and __exit__ methods.

for example in spinn_front_end_common\interface\interface_functions\database_interface.py

**Comment by dkfellows** [comment]
The problem was that `__enter__` was returning `None`, not `self`.
