### ISSUE TITLE
Bad code in ranged dictionary implementation

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNUtils#37]
Looking at the [`set_value_by_ids` method of `spinn_utilities.ranged._IdsView`](https://github.com/SpiNNakerManchester/SpiNNUtils/blob/master/spinn_utilities/ranged/ids_view.py#L27):

```python
    def set_value_by_ids(self, key, ids, value):  # @UnusedVariable
            self._value_lists[key].set_value_id(id=id, value=value)
```

I see that the variable `ids` is unused and `id` is a variable otherwise not mentioned in the body of the method. And the body is wrongly indented too. It looks like an iteration line (perhaps `for id in ids:`) is missing? The code as it stands cannot work as expected.

**Comment by alan-stokes** [comment]
think the 16 day ago commit means this is closeable. reopen if not
