### ISSUE TITLE
Problems with abstract list

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNUtils#38]
In `spinn_utilities.ranged.AbstractList`, we have a range (hah!) of subtle problems. The nasty ones are that we have circular imports (even if they work at runtime, they cause static analysis tools to grumble, and rightly so!) and we also have methods where passing in a non-`AbstractList` (against the method contract) just results in the methods returning an unexpected `None`.

I don't like this. I don't like this at all.

**Comment by Christian-B** [comment]
Alternative is mutliple classes in one file.

In this case that is reasonably ok as the two classes to be moved in would normally only be created by the AbstractList class in whose file they would reside.

**Comment by Christian-B** [comment]
As for "have a range (hah!) of subtle problem" be more specific or this comment will be ignored.

**Comment by Christian-B** [comment]
non-AbstractList extended to support numerical otheer or raise exception.

**Comment by alan-stokes** [comment]
fixed i persume, reopen if not
