### ISSUE TITLE
Python3.7

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNUtils#75]
This issue effects all repositories but is collected here.  Do not create issues in other repositories.

Includes: Should be independent but possible higher level fail until lower fixed.
 
All repositories we remembered are now doing python3.7 testing
(NOT doing any PyNN 0.7 repositories!!!!!!!!!)

The python developers have tweaked again! And too bad for everyone else including us.

https://www.python.org/dev/peps/pep-0479/

-

DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

-
getargspec is depricated 

try:
    from inspect import getfullargspec
except ImportError:
    # Python 2.7 hack
    from inspect import getargspec as getfullargspec

**Comment by Christian-B** [comment]
@dkfellows says:
sPyNNaker/spynnaker/pyNN/models/neural_properties/neural_parameter.py has a potentially troublesome case

PACMAN/pacman/operations/routing_info_allocator_algorithms/malloc_based_routing_allocator/key_field_generator.py

rig/rig/machine_control/scp_connection.py (maybe…)

**Comment by dkfellows** [comment]
Note that we're starting to get users wanting to run against 3.7, so this issue is important to resolve for the 5.0 release.

**Comment by Christian-B** [comment]
I will do some more dependency removal on separate branches.

**Comment by dkfellows** [comment]
Phase two: deal with the new deprecation warnings, and do more integration testing.

**Comment by Christian-B** [comment]
Also created https://github.com/NeuralEnsemble/python-neo/issues/646

**Comment by Christian-B** [comment]
Warning on jsonschema/compat.py:6 is NOT a problem as they do:
try:
    from collections import MutableMapping, Sequence  # noqa
except ImportError:
    from collections.abc import MutableMapping, Sequence  # noqa

**Comment by Christian-B** [comment]
For python3.8 we will have to update urllib3 to >= 1.23

**Comment by Christian-B** [comment]
python3.8 requires MarkupSafe >= 1.1  which comes in via spinx

**Comment by Christian-B** [comment]
requests may also need upgrading

**Comment by Christian-B** [comment]
I have used python3.7 and this appears to be working
