### ISSUE TITLE
replacing all instances of pattern in the absolute path

### ISSUE THREAD

**Issue by mpuzovic** [SpiNNakerManchester/SpiNNUtils#77]
Line https://github.com/SpiNNakerManchester/SpiNNUtils/blob/master/spinn_utilities/make_tools/converter.py#L127 replaces all instances source basename with dest basename in the absolute path. This script is used by Makefiles in SpiNNFrontEndCommon (for example, https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/c_common/front_end_common_lib/Makefile#L50).

This means that if I clone SpiNNFrontEndCommon to directory, say,

/home/me/src/SpiNNFrontEndCommon 

then when invoking converter.py from above Makefile in SpiNNFrontEndCommon it will try to go from directory

/home/me/src/SpiNNFrontEndCommon/c_common/front_end_common_lib/src 

to

/home/me/modified_src/SpiNNFrontEndCommon/c_common/front_end_common_lib/modified_src

instead of

/home/me/src/SpiNNFrontEndCommon/c_common/front_end_common_lib/modified_src

One way to deal with this problem is to only replace relative paths instead of absolute path. I have attached patch that tries to do that and works for my case. 
[relative_dir.patch.gz](https://github.com/SpiNNakerManchester/SpiNNUtils/files/2919059/relative_dir.patch.gz)

**Comment by Christian-B** [comment]
better fix is to just replace the last place.
