### ISSUE TITLE
Field not in slots

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNUtils#85]
https://github.com/SpiNNakerManchester/SpiNNUtils/blob/b978d00593c8ca2186d68a86e152284d4faf5991/spinn_utilities/make_tools/file_converter.py#L404

https://github.com/SpiNNakerManchester/SpiNNUtils/blob/b978d00593c8ca2186d68a86e152284d4faf5991/spinn_utilities/make_tools/file_converter.py#L409

The `_file_name` field is not listed in the class's `__slots__`, nor is it ever assigned anywhere. If the exception (which this is preparing a message for) is ever thrown, it won't be thrown and a totally mysterious other exception will be thrown instead. Please fix.

**Comment by dkfellows** [comment]
While you're at it…

https://github.com/SpiNNakerManchester/SpiNNUtils/blob/b978d00593c8ca2186d68a86e152284d4faf5991/spinn_utilities/make_tools/file_converter.py#L96

The `src` probably ought to be `self._src` there.

**Comment by dkfellows** [comment]
(These were all non-trivial issues spotted by pylint, but not ones on code paths that are normally exercised.)

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNUtils/pull/89
